/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PetService } from "../pet.service";
import { PetCreateInput } from "./PetCreateInput";
import { Pet } from "./Pet";
import { PetFindManyArgs } from "./PetFindManyArgs";
import { PetWhereUniqueInput } from "./PetWhereUniqueInput";
import { PetUpdateInput } from "./PetUpdateInput";
import { SubscriptionFindManyArgs } from "../../subscription/base/SubscriptionFindManyArgs";
import { Subscription } from "../../subscription/base/Subscription";
import { SubscriptionWhereUniqueInput } from "../../subscription/base/SubscriptionWhereUniqueInput";

export class PetControllerBase {
  constructor(protected readonly service: PetService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Pet })
  async createPet(@common.Body() data: PetCreateInput): Promise<Pet> {
    return await this.service.createPet({
      data: data,
      select: {
        bio: true,
        createdAt: true,
        dateOfBirth: true,
        healthCondition: true,
        id: true,
        location: true,
        mainGalleryPhotos: true,
        name: true,
        numberOfOwners: true,
        personalityTraits: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Pet] })
  @ApiNestedQuery(PetFindManyArgs)
  async pets(@common.Req() request: Request): Promise<Pet[]> {
    const args = plainToClass(PetFindManyArgs, request.query);
    return this.service.pets({
      ...args,
      select: {
        bio: true,
        createdAt: true,
        dateOfBirth: true,
        healthCondition: true,
        id: true,
        location: true,
        mainGalleryPhotos: true,
        name: true,
        numberOfOwners: true,
        personalityTraits: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Pet })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async pet(@common.Param() params: PetWhereUniqueInput): Promise<Pet | null> {
    const result = await this.service.pet({
      where: params,
      select: {
        bio: true,
        createdAt: true,
        dateOfBirth: true,
        healthCondition: true,
        id: true,
        location: true,
        mainGalleryPhotos: true,
        name: true,
        numberOfOwners: true,
        personalityTraits: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Pet })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePet(
    @common.Param() params: PetWhereUniqueInput,
    @common.Body() data: PetUpdateInput
  ): Promise<Pet | null> {
    try {
      return await this.service.updatePet({
        where: params,
        data: data,
        select: {
          bio: true,
          createdAt: true,
          dateOfBirth: true,
          healthCondition: true,
          id: true,
          location: true,
          mainGalleryPhotos: true,
          name: true,
          numberOfOwners: true,
          personalityTraits: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Pet })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePet(
    @common.Param() params: PetWhereUniqueInput
  ): Promise<Pet | null> {
    try {
      return await this.service.deletePet({
        where: params,
        select: {
          bio: true,
          createdAt: true,
          dateOfBirth: true,
          healthCondition: true,
          id: true,
          location: true,
          mainGalleryPhotos: true,
          name: true,
          numberOfOwners: true,
          personalityTraits: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/subscriptions")
  @ApiNestedQuery(SubscriptionFindManyArgs)
  async findSubscriptions(
    @common.Req() request: Request,
    @common.Param() params: PetWhereUniqueInput
  ): Promise<Subscription[]> {
    const query = plainToClass(SubscriptionFindManyArgs, request.query);
    const results = await this.service.findSubscriptions(params.id, {
      ...query,
      select: {
        createdAt: true,
        endDate: true,
        id: true,

        pet: {
          select: {
            id: true,
          },
        },

        startDate: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/subscriptions")
  async connectSubscriptions(
    @common.Param() params: PetWhereUniqueInput,
    @common.Body() body: SubscriptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      subscriptions: {
        connect: body,
      },
    };
    await this.service.updatePet({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/subscriptions")
  async updateSubscriptions(
    @common.Param() params: PetWhereUniqueInput,
    @common.Body() body: SubscriptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      subscriptions: {
        set: body,
      },
    };
    await this.service.updatePet({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/subscriptions")
  async disconnectSubscriptions(
    @common.Param() params: PetWhereUniqueInput,
    @common.Body() body: SubscriptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      subscriptions: {
        disconnect: body,
      },
    };
    await this.service.updatePet({
      where: params,
      data,
      select: { id: true },
    });
  }
}
