/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsString,
  MaxLength,
  IsOptional,
  IsDate,
  IsInt,
  Min,
  Max,
  IsEnum,
  ValidateNested,
} from "class-validator";

import { Type } from "class-transformer";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { EnumPetPersonalityTraits } from "./EnumPetPersonalityTraits";
import { SubscriptionUpdateManyWithoutPetsInput } from "./SubscriptionUpdateManyWithoutPetsInput";

@InputType()
class PetUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  bio?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  dateOfBirth?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  healthCondition?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  location?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  mainGalleryPhotos?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  numberOfOwners?: number | null;

  @ApiProperty({
    required: false,
    enum: EnumPetPersonalityTraits,
    isArray: true,
  })
  @IsEnum(EnumPetPersonalityTraits, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumPetPersonalityTraits], {
    nullable: true,
  })
  personalityTraits?: Array<"Option1">;

  @ApiProperty({
    required: false,
    type: () => SubscriptionUpdateManyWithoutPetsInput,
  })
  @ValidateNested()
  @Type(() => SubscriptionUpdateManyWithoutPetsInput)
  @IsOptional()
  @Field(() => SubscriptionUpdateManyWithoutPetsInput, {
    nullable: true,
  })
  subscriptions?: SubscriptionUpdateManyWithoutPetsInput;
}

export { PetUpdateInput as PetUpdateInput };
